# Generated by Django 3.2 on 2021-04-30 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='eamil',
            new_name='email',
        ),
    ]
